Home page edits v1
Holiday-Secret-Santa/Secret-Santa-App pull request #74
Opened 2020-09-21 23:58 UTC by valeglezleyva

2020-09-22 10:58 UTC, ystamaritq commented on client/public/index.html
> +
This was removed in the previous PRs, please remove it! Thanks

2020-09-22 11:00 UTC, ystamaritq requested changes

2020-09-22 13:25 UTC, JDMartinez1531 approved these changes

2020-09-22 13:48 UTC, ystamaritq reviewed
Looks great! But, I will approve as soon as code-climate passes. Thanks 

![image](https://user-images.githubusercontent.com/30836140/93890926-77a58000-fcb0-11ea-94d8-31a181a9d999.png)

2020-09-22 17:41 UTC, KEDuran submitted a review, later dismissed
Hi Vale :) Great job! Code climate is still not passing. Please refactor and then I will approve. Thanks!

2020-09-23 03:41 UTC, ystamaritq approved these changes
Looks great! Great job. Issues resolved

2020-09-23 03:47 UTC, merged